### ISSUE TITLE
Annotation of "a thuilleadh", "a lán"

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#105]
These are currently fixed, and this leads to some incorrect analyses.

A good case is sentence 1713 that starts "B'fhéidir nach mbeadh a thuilleadh achrainn ann".

"tuilleadh" should be the head here, and the subject of the sentence.  All subjects in Irish should be Case=NomAcc, and that's currently true across the treebank except for these cases with "a thuilleadh" (and a few similar ones with "níos mó X").   The genitive case on "achrainn" should be triggered by it being nmod of "tuilleadh" but currently this is flipped around with "a" as nmod of "achrainn".  Both of these currently must be treated as exceptions when they're really not.

Same story with "a lán".  In both cases, "a" should probably be tagged DET, certainly not NOUN.

**Comment by tlynn747** [comment]
Yes I agree. That was an automatic conversation of fixed phrases in the original data, where underscores were present. a_thuilleadh etc

'a' being a possessive determiner: DET	Det	Gender=Masc|Number=Sing|Person=3|Poss=Yes
