### ISSUE TITLE
Review needed of "dar le" (according to) annotations in IUDT

### ISSUE THREAD

**Issue by tlynn747** [UniversalDependencies/UD_Irish-IDT#11]
_Dar le_ 'according to' is inconsistently labelled throughout the Irish treebank.  

This probably derives from the conflict between its syntactic makeup (VERB + ADP) and its grammatical role. 
Note that _Dar_ is in the present indicative form, present tense (not a gerund, which in Irish is denoted by the Verbal Noun form)

Other treebank-research (based on my language knowledge!):
In the English treebanks, the attachment of the entire "According to X" phrase varies from obl, to advcl and advmod, with obl being the most prominent.  The "according to" phrase is attached as fixed (POS tags are VERB (gerund) and ADP), with an attachment to X as case.

In French (selon) and Italian (secondo) all treebanks seem to also use obl.

### problem 1 
_Dar léi, ólann milliún duine caife in Éirinn_ 'According to her, 1m people drink coffee in Ireland'

The problem for Irish is the following. Applying the "fixed" label is problematic as the preposition (to) can inflect for number and person.
Dar liom - according to me
Dar leat - according to you
Dar leis - according to him
Dar leis an bean - according to the woman
Dar leis an file - according to the poet

(In the future (with more resources at hand!) we might split out the pronominal objects to become separate tokens, but for now we will keep the tokenisation as is. )

For this reason we've attached these instances of _dar le_ as parataxis, discourse or assigned them as the root of the phrase.

### problem 2
In some cases, _Dar le X_ is a clear separate clause that can be omitted and therefore considered an optional argument (adjunct).
e.g. According to him, there were too few people wearing masks -> there were too few people wearing masks

But it seems that in Irish it's possible to treat Dar as a matrix verb that is followed by a ccomp:
_Dar leis **go bhfuil sé de dhualgas ar gach duine**...._ (lit. According to him **that** it is everyone's responsibility to...) 'According to him it's everyone's responsibility to...'

_go_ is a complementiser in Irish, so the conventional manner for attaching Dar can't apply here.

Further discussion required and review of data needed prior to v2.7 release.

**Comment by tlynn747** [comment]
@kscanne and @colinbatchelor any thoughts on this one?

**Comment by kscanne** [comment]
This really needs to be tagged for what it is; (defective) VERB + ADP.  This solves both problems above. "According to" isn't the best cross-lingual comparison... "dar liom" behaves more like English  "Seems to me..." syntactically, which would surely be tagged VERB + PP.  Same with "dar leis go bhfuil...", best compared with "Seems to him that..."

**Comment by tlynn747** [comment]
I'm in agreement with the POS-tagging, the main question was how to attach it to other clauses.  

Dar leis go bhfuil sé de dhualgas ar gach duine - root + ccomp
Dar léi, ólann milliún duine caife in Éirinn - ólann as parataxis?
 Casadh eochair i nglas a raibh meirg na mblianta air, dar leat, ón díoscán gránna a rinne sé agus b'iúd an doras ar leathadh romham.  - mid sentence, parataxis/ discourse?

**Comment by kscanne** [comment]
Yes, ccomp in the first case, and parataxis in the others.

**Comment by tlynn747** [comment]
Reviewed and updated
