### ISSUE TITLE
Annotation of "leith"

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#113]
In phrases like "ar leith", "i leith", this is a special dative form of "leath" — see https://www.teanglann.ie/ga/fgb/leath

@tlynn747: is it OK if I change lemma to "leath" and add "Case=Dat" to these?

I won't mess with the deprels (many are fixed... happy to leave those as they are for now).

**Comment by tlynn747** [comment]
Sure, those lemmas were inherited from the rule-based tagger. But leath makes sense and more Dative markers would be great!
