### ISSUE TITLE
Polarity guidelines

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#124]
This feature is used on particles and copulas (ní, nach, etc.) and the combined form níl (VERB). That all looks good. But it occasionally appears on a verb even when not combined with the negating particle (cf. "ní bheidh" in sentence 1068).   

We should make this consistent one way or the other and clarify the guidelines. I'd be inclined to say Polarity=Neg _shouldn't_ apply to verbs (except for "níl") since it's not a morphological feature of the verb itself. Indeed the general UD guidelines suggest this: "In languages that negate using a function word, Polarity is used to mark that function word"

Easy fix either way, just looking for guidance which is the preferred approach.

**Comment by tlynn747** [comment]
This again is inherited from the original PAROLE tagging on the NCI data. 
My understanding of it being marked on the VERB was that it was accounting for the lenition as a morphological feature:
beidh -> ní bheidh
feicim -> ní fheicim
etc

I'm always in favour of richer data where possible so I'd be inclined to keep it. I agree with the need for consistency though.

**Comment by kscanne** [comment]
That's fine, but I'm going to mark this as an enhancement and tackle it later then.
