### ISSUE TITLE
Inconsistency in Determiner features

### ISSUE THREAD

**Issue by tlynn747** [UniversalDependencies/UD_Irish-IDT#13]
Appears to be features missing for some determiners in v2.6  (which has impact on v2.7 predicted features!)

an	an	DET	Art	PronType=Art
should be
an	an	DET	Art   Definite=Def|Number=Sing|PronType=Art

**Comment by tlynn747** [comment]
Also need to address plural forms
na	na	DET	Art	PronType=Art

could be:
na	na	DET	Art	Definite=Def|Number=Plur|PronType=Art
or
na	na	DET	Art	Case=Gen|Definite=Def|Gender=Fem|Number=Sing|PronType=Art

i.e. need to watch out for genitive cases so don't do a global replace

**Comment by michealjohnny** [comment]
add also:

na na DET Art Case=Gen|Definite=Def|Number=Plur|PronType=Art

e.g. "ar dhoirse **na** seomraí"
on the doors of the rooms.
