### ISSUE TITLE
Annotation of "ar tí" and "in ann"

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#132]
These are syntactically similar constructions: "tá mé ar tí X a dhéanamh" or "tá mé in ann X a dhéanamh".  Both are an ADP followed by a NOUN.

https://www.teanglann.ie/ga/fgb/t%C3%AD
https://www.teanglann.ie/ga/fgb/t%C3%AD  (entry **ann^2**)

There's some inconsistency in how they're handled currently.  Both are often given PrepForm=Cmpd feature and those should certainly be removed since these aren't compound prepositions.  (Though I'm ok if you want to keep them as fixed). 

More interesting is to decide how they attach to the surrounding sentence.  In the examples above, which are typical, both should be xcomp:pred of the main verb (and usually are in the treebank).  The tricky part is how to attach the infinitive that follows. Wondering if these should be examples of "acl" as in issue #86, attached to tí/ann?   This is how the analogous sentence "I am on the point of doing X" would be handled in the English treebank if I understand correctly.

**Comment by tlynn747** [comment]
My favourite Irish phrase :)

Yes "fixed" seems a good option for the treatment of the phrase a a whole.  And being treated as a predicate of 'bí' also sits well with me.
I don't have any problem with two xcomps in a row, if perhaps it is two open complement phrases.

In that case for _tá trí thogra abalone ar tí infheistíocht a dhéanamh in áiseanna fáis._ we'd have:

xcomp:pred(_tá, ar_)
fixed(_ar, tí_)
xcomp(_ar, dhéanamh_)
obj(_dhéanamh, infheistíocht_)

The definition for [acl](https://universaldependencies.org/u/dep/all.html#acl-clausal-modifier-of-noun-adnominal-clause) is: "acl stands for finite and non-finite clauses that modify a nominal"
If we treat _ar tí_ as a PP predicate then I don't think we can use acl for the infinitive that follows.

The way I interpret acl is like a relative clause that's missing "who/ that/ which/ in which, etc"
There are many online sites (that are) offering booking facilities
I have a parakeet (who is) named cookie
I just want a simple way (in which) to get my discount

**Comment by kscanne** [comment]
Ok — I'll need to go back and look at the English examples that inspired me to file this!

Do you agree at least with removing PrepForm=Cmpd from these two?  Neither is in the list of compound prepositions in the Christian Brothers (nor in your [PrepForm documentation](https://universaldependencies.org/ga/feat/PrepForm.html)), and are completely different syntactically (no nominal head in the genitive, etc.).

**Comment by tlynn747** [comment]
Yes definitely agree with removing PrepForm=Cmpd. Sorry - I went looking through the _ar tí_ examples and couldn't see those features, so assumed they got cleaned up in our recent work!
