### ISSUE TITLE
Cliath features

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#133]
In "Baile Átha Cliath", I think "Cliath" should be tagged Case=Gen|Gender=Fem|Number=Plur — looks to be masculine singular currently, maybe as a consequence of the de-flatting process of named entities?  Any reason not to fix these? Wanted to check first since there are 400+ of them.  cc @michealjohnny

**Comment by michealjohnny** [comment]
Yep, had a look over the possibilities a short while ago and I think this change is good to go.
