### ISSUE TITLE
Is Definite=Ind needed?

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#156]
I've been working under the assumption that definite nouns should get the feature Definite=Def, and all others simply leave this feature out (see PR #88 where I added Definite=Def to 13,000+ tokens). But I see there are 29 words annotated with Definite=Ind in the treebank.  Would it be simpler to just remove these features?  I don't see any rhyme or reason to why these particular words were given Definite=Ind vs. all of the other indefinite nouns.  Most are surface tokens "gnóthaí" or "oibre" which suggests some machine-learned weirdness.

There's a note in the docs about words inflecting to show indefiniteness but I'm not sure what that means:
https://universaldependencies.org/ga/feat/Definite.html

**Comment by kscanne** [comment]
Thanks for tracking that down — makes sense.  

I looked at the Definite feature in several other treebanks and it appears to be used for determiners (a vs the in English) and not nouns, so I'm not sure there's much cross-linguistic value  in adding Definite=Ind everywhere.

**Comment by rueter** [comment]
You might want to look at how the Scandinavian languages deal with their definite and indefinite nouns. They are morphologically marked for plural and definiteness, and yet both Number=Sing and Definiteness=Ind are found in features.

**Comment by tlynn747** [comment]
OK so. Happy for the nouns to be labelled with morph features as per their marking. i.e. no marking, no features labelled.
