### ISSUE TITLE
Review of gender features needed

### ISSUE THREAD

**Issue by tlynn747** [UniversalDependencies/UD_Irish-IDT#17]
Predicted gender morph features need to be manually reviewed in the v2.7 expansion trees - ie sentences numbered 2925 onwards. 
This includes Nouns, Proper Nouns and Adjectives.  

Native speaker/linguist needed for this task.

**Comment by kscanne** [comment]
Nouns fixed in #53 and #54. On to PROPN/ADJ...

**Comment by kscanne** [comment]
Note to self: realizing some care is needed in copying NOUN features to ADJs which are amod in case of singular noun but plural adjective: "dhá sheol úra".

**Comment by kscanne** [comment]
Closing as remaining cases fall under #23.
