### ISSUE TITLE
Adjective feature review in predicted trees

### ISSUE THREAD

**Issue by tlynn747** [UniversalDependencies/UD_Irish-IDT#23]
Need a full review of adjective features - most bugs are in the predicted data in the training file (data added in v2.7, sents 2923 onwards)

Review will need to be carried out by native speaker who can assess:

NounType (Broad or Slender)
Gender (of preceding noun)
Case - if Common case or Genitive.

Worth referring to earlier data in the treebank  (v2.6 and earlier= sents up to 2923) to see what features were captured and should be captured 

Have already reviewed lenition feature.

**Comment by kscanne** [comment]
As noted in issue #17: ...some care is needed in copying NOUN features to ADJs which are amod in case of singular noun but plural adjective: "dhá sheol úra".
