### ISSUE TITLE
Annotate impersonal verb forms with Person=0

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#36]
Following the discussion [here](https://github.com/UniversalDependencies/docs/issues/746), for the sake of consistency with other treebanks.

This would be a trivial substitution (Person=0 in place of Voice=Auto) which I'd be happy to do pending @tlynn747 's approval!

**Comment by tlynn747** [comment]
Yes - in favour of this.

Documentation will need to be updated - along with relevant feature files
