### ISSUE TITLE
Fix some bad lemmatizations

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#40]
There are about 100-110 examples where I presume the machine-learned lemmatizer produced an incorrect lemma and these weren't manually corrected.  I mean examples like
forálacha->forál
cuideachtaí->cuideacht
ainmneacha->ainmn
etc.

Patch coming!

**Comment by tlynn747** [comment]
Brilliant. Thanks. Human error in the review process. We'll put it down to their annotator fatigue!

**Comment by kscanne** [comment]
Yup, I understand well!  I'm going to wait until you click through on the open pull request to avoid potential merge conflicts.

**Comment by kscanne** [comment]
So it turns out there were more like 800 incorrect lemmas. We should figure out a way to build in some QA checks using my data to validate surface form/lemma/POS tag. About to submit the PR....
