### ISSUE TITLE
Handle prefixes consistently

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#41]
Most of the time prefixes like neamh-, comh-, etc. are preserved in the lemma ("neamhfhicsean" as the lemma of "neamhfhicsin" for example), but other times they are removed ("pósta" as the lemma of "neamhphósta" in sentence 3587).  I'd be very much in favor of keeping the prefixes since words like "neamhphósta" are treated as headwords in Irish dictionaries. This seems to be the majority approach in the treebank as well.  Will be tricky to cleanup in an automated way but I'm willing to give it a try, with @tlynn747 's OK!

**Comment by tlynn747** [comment]
Yes I agree with this.  It was always hard to establish the best way as a lot of the inconsistency came from the original NCI-I tagged corpus so it was hard to establish a pattern!  

In favour of keeping it consistent with this suggestion.
