### ISSUE TITLE
Re-evaluate features on imperfect verbs

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#51]
I'm looking at examples like sentence 941 with an imperfect/past habitual main verb:

    # sent_id = 941
    # text = Chuiridís oilithrigh amach go dtí Compostela mar ionadaithe thar cionn a muintire go léir agus bhailítí airgead chuige sin sa Chladach.
    1   Chuiridís   cuir    VERB    VTI Form=Len|Mood=Imp|Number=Plur|Person=3|Tense=Past   0   root    _   _
    2   oilithrigh  oilithreach NOUN    Noun    Case=NomAcc|Gender=Masc|Number=Plur 1   obj _   _
    3   amach   amach   ADV Dir _   1   advmod  _   _

But in the UD guidelines Mood=Imp means imperative mood (https://universaldependencies.org/u/feat/Mood.html).  Should this be Tense=Imp and indicative mood? Or Aspect=Imp?

**Comment by tlynn747** [comment]
Good catch. This is definitely an oversight in our mapping from the PAROLE tagset to UD. 

I've checked out mapping file and we actually had a note to say: 
PastImp	Mood=Imp|Tense=Past		Note that Aspect=Imp is also a possibility. 

Strange it wasn't picked up in the more recent use of that file in retrieving morphological information for the rest of the NCI data (ie the data added on after the initial release of 1200 trees). I remember asking for that file to be reviewed and to make sure the v2 mappings were correct...

We seem to use Mood=Imp for the imperative verbs also, which is correct thankfully!!

**Comment by kscanne** [comment]
Ok, I'm going to use Aspect=Imp for now (though I don't really understand the distinction between Tense=Imp and Aspect=Imp|Tense=Past — guidelines mention examples in Bulgarian).  This corrects the error at least and we can discuss the finer grammatical points another time :D  

I'll note also that Aspect=Hab|Tense=Past could work too since that's really the sense in Irish.

Command for future reference:

`sed -i '/VERB.*Mood=Imp.*Tense=Past/s/\t\([^\t]*\)Mood=Imp|/\tAspect=Imp|\1/' *.conllu`

**Comment by kscanne** [comment]
Also, the Irish documentation for Imperative has an incorrect example (in fact it's the one from sentence 941 that I pointed out above).  That means "They used to send pilgrims out", not "Let them send..."

https://universaldependencies.org/ga/feat/Mood.html
