### ISSUE TITLE
faoi bhráid — compound preposition?

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#65]
Sometimes this is tagged as a compound preposition and other times like a normal PP with a genitive nmod.  I'd be inclined toward the latter.... I'm always happier with fewer fixed relations!

**Comment by kscanne** [comment]
Also "fé bhráid" in the corpus.

**Comment by tlynn747** [comment]
Apparently it's taken from the Christian Brothers grammar. If this is contested then would that mean all others would be also , on the basis that the genitive is in use in the following noun. I think there's sufficient examples of compound preposition + noun (Gen) to allow a tagger/parser to correctly learn this pattern.

**Comment by kscanne** [comment]
That's fine — I'll make them all compounds. I mostly care about consistency at this point.

**Comment by michealjohnny** [comment]
I see ye may have settled this - I would just add that it can, when not followed by a noun, be a simple prepositional structure. 
It **definitely** need not always be a compound prepostion - it's just that this is by far its most common use. 

Teoiric a thabhairt faoi bhráid (to put forward/present a theory). 
-VS- 
Teoiric a chur faoi bhráid an choiste  (to put forward present a theory to the committee).

The first example here the simpler prep and is quite archaic in my opinion. I can't imagine it coming up very often at all, and I'm 99% sure it'll only come up after "tabhair" or "tóg" while the latter will follow verbs like "cuir", "téigh", "tar" - if that's any help.
Perhaps when making them all compounds you could extend the lookup to check if anything follows the preositional structure.

The latter is the compound prep.

**Comment by kscanne** [comment]
cf. full list of compounds here: https://universaldependencies.org/ga/feat/PrepForm.html

**Comment by kscanne** [comment]
Fixed by #134
