### ISSUE TITLE
Tags on bliana, fichid, uaire, cinn after numerals

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#70]
These are usually tagged Case=Gen in the treebank currently, but are usually considered "special" plural forms that only occur after 3...10. See Christian Brothers p.77 and FGB which specifically marks _bliana_, _fichid_, _uaire_ as "pl. with numerals". Give me the green light and I'll fix 'em (manually, probably).

**Comment by kscanne** [comment]
For reference:
https://www.teanglann.ie/en/fgb/bliain
https://www.teanglann.ie/en/fgb/fiche
https://www.teanglann.ie/en/fgb/uair
https://www.teanglann.ie/en/fgb/ceann

**Comment by tlynn747** [comment]
Happy with all of these fixes!
