### ISSUE TITLE
PROPN vs. NOUN on nationalities

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#72]
Words like "Meiriceánach", "Sasanach", "Éireannach" are currently tagged as PROPN in the treebank. But the guidelines suggest that PROPN should be used only for nouns that are "the name (or part of the name) of a specific individual, place, or object".  

https://universaldependencies.org/u/pos/PROPN.html

Tagging these as NOUN would also have the advantage that any PROPN would (I think) then automatically be Definite=Def (the nationalities wouldn't get that tag without a preceding determiner), and those tags could be propagated to heads in noun phrases like "leabhar Chaoimhín".

**Comment by dan-zeman** [comment]
I cannot comment on the definiteness issue but just wanted to note that rules for `PROPN` should be language-specific, and the semantic list in the universal guidelines is an approximation, as I understand it. FWIW, in the Czech grammar names of nationalities are also proper names, hence we tag them `PROPN` in UD.

**Comment by michealjohnny** [comment]
From what I can see "Meiriceánach", "Sasanach", "Éireannach" are all used in the same way as other proper nouns in Irish.  They are always capitalised for starters. The only thing I wanted to check was their grammatical desciptions in reference documents, because they are treated differently to other nouns in certain situations.
Other Irish proper nouns, such as "Seán" or "Eoin" will have a gender and declension, Masc1 and Masc4 respectively, in the same way these nationality words do.
This suggests to me the PROPN tagging is correct.

**Comment by kscanne** [comment]
But they aren't used the same way grammatically.  I'm proposing a definition of PROPN which aligns with the notion of definiteness in Irish.  A word like "Meiriceánach" by itself is of course indefinite and therefore behaves very differently from "Meiriceá", e.g. without a definite article it wouldn't make a noun phrase definite as happens with "Stáit Aontaithe Mheiriceá".  What would an alternative definition look like?

**Comment by michealjohnny** [comment]
Yeah, after reflecting on it my point about casing+gender for these words was far too shallow. They (Meiriceánach, Éireannach, etc)  are neither conceptually the same as a proper noun, nor as definite as a proper noun, nor are they treated in the same way as proper nouns by Irish grammar.

**Comment by tlynn747** [comment]
This is an interesting one! In some cases of course the nationality will be an ADJ, and in others it has nominal properties. I think the definiteness argument makes sense for the latter because of the lack of indefinite article in Irish.
