### ISSUE TITLE
Merge PronType=Emp and Form=Emp?

### ISSUE THREAD

**Issue by tlynn747** [UniversalDependencies/UD_Irish-IDT#97]
Cleaning up the documentation on emphatic pronouns, I realise there are two ways in which the emphatic form is noted in the data:
Nouns and Verbs: Form=Emp   (mo chroíse, im thuairimse, a deirimse)
Pronouns and prepositions = PronType=Emp  (agamsa, mise) 

Would it make more sense to replace the PronType=Emp with Form=Emp (or add it to a potential list of Form values) for pronouns or would there be a good reason for keeping the "type"?

**Comment by colinbatchelor** [comment]
I plumped for `Form=Emp` when I was doing some tidying of gd recently for the very same reason. Seems to be orthogonal to the other sorts of `PronType`.

Thinking about `Form` I did wonder whether it was a better home for `Slender` and `NotSlender` than `NounType` but that would be another issue.

**Comment by tlynn747** [comment]
Great to get this feedback 👌

**Comment by tlynn747** [comment]
Colin - just seeing your issue 7 on the Scottish Treebank.... thanks for the link to PronType https://universaldependencies.org/u/feat/PronType.html

Which makes reminds me now that [Form](https://universaldependencies.org/ga/feat/Form.html) is a language specific feature we introduced for Irish while PronType=Emp is a UD feature   (e.g. himself in English)

So maybe changing it Form=Emp or pronouns is not such a good idea after all as we lose the multilingual aspect of consistency across treebanks.

**Comment by kscanne** [comment]
I agree no change is needed here — vote for closing as WONTFIX.
