### ISSUE TITLE
Annotation of trasna

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#98]
trasna is currently annotated as PART, with feature PartType=Inf.  Not sure what this means.  In most cases it should be ADP with a genitive noun, e.g. sentence 2245 "trasna an bhóthair", sentence 2914 "trasna an Atlantaigh", srl.

**Comment by tlynn747** [comment]
Good catch. It's because it's tagged like that (consistently) in the Elaine's NCI tagged corpus
trasna trasna+Part+Inf 

agree with the ADP change
